Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/kconfigwidgets' : '@same'
    'frameworks/kwidgetsaddons' : '@same'
    'frameworks/kitemviews' : '@same'
    'frameworks/karchive' : '@same'

Options:
  test-before-installing: True
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows', 'Android' ]
